//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedBinaryFormatter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedBinaryFormatter.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtable&apos;s capacity overflowed and went negative. Check load factor, capacity and the current size of the table..
        /// </summary>
        public static string Arg_HTCapacityOverflow {
            get {
                return ResourceManager.GetString("Arg_HTCapacityOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters &apos;members&apos; and &apos;data&apos; must have the same length..
        /// </summary>
        public static string Argument_DataLengthDifferent {
            get {
                return ResourceManager.GetString("Argument_DataLengthDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FieldInfo object is not valid..
        /// </summary>
        public static string Argument_InvalidFieldInfo {
            get {
                return ResourceManager.GetString("Argument_InvalidFieldInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot supply both a MemberInfo and an Array to indicate the parent of a value type..
        /// </summary>
        public static string Argument_MemberAndArray {
            get {
                return ResourceManager.GetString("Argument_MemberAndArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When supplying a FieldInfo for fixing up a nested type, a valid ID for that containing object must also be supplied..
        /// </summary>
        public static string Argument_MustSupplyContainer {
            get {
                return ResourceManager.GetString("Argument_MustSupplyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When supplying the ID of a containing object, the FieldInfo that identifies the current field within that object must also be supplied..
        /// </summary>
        public static string Argument_MustSupplyParent {
            get {
                return ResourceManager.GetString("Argument_MustSupplyParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member at position {0} was null..
        /// </summary>
        public static string ArgumentNull_NullMember {
            get {
                return ResourceManager.GetString("ArgumentNull_NullMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectID cannot be less than or equal to zero..
        /// </summary>
        public static string ArgumentOutOfRange_ObjectID {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_ObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information..
        /// </summary>
        public static string BinaryFormatter_SerializationDisallowed {
            get {
                return ResourceManager.GetString("BinaryFormatter_SerializationDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read beyond the end of the stream..
        /// </summary>
        public static string IO_EOF_ReadBeyondEOF {
            get {
                return ResourceManager.GetString("IO_EOF_ReadBeyondEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array type &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_ArrayType {
            get {
                return ResourceManager.GetString("Serialization_ArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array element type is Object, &apos;dt&apos; attribute is null..
        /// </summary>
        public static string Serialization_ArrayTypeObject {
            get {
                return ResourceManager.GetString("Serialization_ArrayTypeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assembly information is available for object on the wire, &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_Assembly {
            get {
                return ResourceManager.GetString("Serialization_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assembly ID for object type &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_AssemblyId {
            get {
                return ResourceManager.GetString("Serialization_AssemblyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find assembly &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_AssemblyNotFound {
            get {
                return ResourceManager.GetString("Serialization_AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary stream &apos;{0}&apos; does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization..
        /// </summary>
        public static string Serialization_BinaryHeader {
            get {
                return ResourceManager.GetString("Serialization_BinaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor to deserialize an object of type &apos;{0}&apos; was not found..
        /// </summary>
        public static string Serialization_ConstructorNotFound {
            get {
                return ResourceManager.GetString("Serialization_ConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BinaryFormatter stream..
        /// </summary>
        public static string Serialization_CorruptedStream {
            get {
                return ResourceManager.GetString("Serialization_CorruptedStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-AppDomain BinaryFormatter error; expected &apos;{0}&apos; but received &apos;{1}&apos;..
        /// </summary>
        public static string Serialization_CrossAppDomainError {
            get {
                return ResourceManager.GetString("Serialization_CrossAppDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} and the types derived from it (such as {1}) are not permitted to be deserialized at this security level..
        /// </summary>
        public static string Serialization_DuplicateSelector {
            get {
                return ResourceManager.GetString("Serialization_DuplicateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object IDs must be greater than zero..
        /// </summary>
        public static string Serialization_IdTooSmall {
            get {
                return ResourceManager.GetString("Serialization_IdTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter..
        /// </summary>
        public static string Serialization_IncorrectNumberOfFixups {
            get {
                return ResourceManager.GetString("Serialization_IncorrectNumberOfFixups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fixup on an object implementing ISerializable or having a surrogate was discovered for an object which does not have a SerializationInfo available..
        /// </summary>
        public static string Serialization_InvalidFixupDiscovered {
            get {
                return ResourceManager.GetString("Serialization_InvalidFixupDiscovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member fixup was registered for an object which implements ISerializable or has a surrogate. In this situation, a delayed fixup must be used..
        /// </summary>
        public static string Serialization_InvalidFixupType {
            get {
                return ResourceManager.GetString("Serialization_InvalidFixupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ....
        /// </summary>
        public static string Serialization_InvalidFormat {
            get {
                return ResourceManager.GetString("Serialization_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only system-provided types can be passed to the GetUninitializedObject method. &apos;{0}&apos; is not a valid instance of a type..
        /// </summary>
        public static string Serialization_InvalidType {
            get {
                return ResourceManager.GetString("Serialization_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with ID {0} implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other..
        /// </summary>
        public static string Serialization_IORIncomplete {
            get {
                return ResourceManager.GetString("Serialization_IORIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberInfo requested for ISerializable type..
        /// </summary>
        public static string Serialization_ISerializableMemberInfo {
            get {
                return ResourceManager.GetString("Serialization_ISerializableMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types not available for ISerializable object &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_ISerializableTypes {
            get {
                return ResourceManager.GetString("Serialization_ISerializableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No map for object &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_Map {
            get {
                return ResourceManager.GetString("Serialization_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberInfo cannot be obtained for ISerialized Object &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_MemberInfo {
            get {
                return ResourceManager.GetString("Serialization_MemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; in class &apos;{1}&apos; is not present in the serialized stream and is not marked with {2}..
        /// </summary>
        public static string Serialization_MissingMember {
            get {
                return ResourceManager.GetString("Serialization_MissingMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with ID {0} was referenced in a fixup but has not been registered..
        /// </summary>
        public static string Serialization_MissingObject {
            get {
                return ResourceManager.GetString("Serialization_MissingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fixup is registered to the object with ID {0}, but the object does not appear in the graph..
        /// </summary>
        public static string Serialization_NeverSeen {
            get {
                return ResourceManager.GetString("Serialization_NeverSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object has never been assigned an objectID..
        /// </summary>
        public static string Serialization_NoID {
            get {
                return ResourceManager.GetString("Serialization_NoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MemberInfo for Object {0}..
        /// </summary>
        public static string Serialization_NoMemberInfo {
            get {
                return ResourceManager.GetString("Serialization_NoMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; in Assembly &apos;{1}&apos; is not marked as serializable..
        /// </summary>
        public static string Serialization_NonSerType {
            get {
                return ResourceManager.GetString("Serialization_NonSerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference..
        /// </summary>
        public static string Serialization_NotCyclicallyReferenceableSurrogate {
            get {
                return ResourceManager.GetString("Serialization_NotCyclicallyReferenceableSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given object does not implement the ISerializable interface..
        /// </summary>
        public static string Serialization_NotISer {
            get {
                return ResourceManager.GetString("Serialization_NotISer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with ID {0} was referenced in a fixup but does not exist..
        /// </summary>
        public static string Serialization_ObjectNotSupplied {
            get {
                return ResourceManager.GetString("Serialization_ObjectNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ObjectTypeEnum {0}..
        /// </summary>
        public static string Serialization_ObjectTypeEnum {
            get {
                return ResourceManager.GetString("Serialization_ObjectTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} has never been assigned an objectID..
        /// </summary>
        public static string Serialization_ObjNoID {
            get {
                return ResourceManager.GetString("Serialization_ObjNoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the containing object cannot be the same as the object ID..
        /// </summary>
        public static string Serialization_ParentChildIdentical {
            get {
                return ResourceManager.GetString("Serialization_ParentChildIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error. Current element is not compatible with the next element, {0}..
        /// </summary>
        public static string Serialization_ParseError {
            get {
                return ResourceManager.GetString("Serialization_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing up a partially available ValueType chain is not implemented..
        /// </summary>
        public static string Serialization_PartialValueTypeFixup {
            get {
                return ResourceManager.GetString("Serialization_PartialValueTypeFixup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object cannot be registered twice..
        /// </summary>
        public static string Serialization_RegisterTwice {
            get {
                return ResourceManager.GetString("Serialization_RegisterTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberInfo type {0} cannot be serialized..
        /// </summary>
        public static string Serialization_SerMemberInfo {
            get {
                return ResourceManager.GetString("Serialization_SerMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to deserialize an empty stream..
        /// </summary>
        public static string Serialization_Stream {
            get {
                return ResourceManager.GetString("Serialization_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Stream encountered before parsing was completed..
        /// </summary>
        public static string Serialization_StreamEnd {
            get {
                return ResourceManager.GetString("Serialization_StreamEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding selector will introduce a cycle..
        /// </summary>
        public static string Serialization_SurrogateCycle {
            get {
                return ResourceManager.GetString("Serialization_SurrogateCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector contained a cycle..
        /// </summary>
        public static string Serialization_SurrogateCycleInArgument {
            get {
                return ResourceManager.GetString("Serialization_SurrogateCycleInArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The internal array cannot expand to greater than Int32.MaxValue elements..
        /// </summary>
        public static string Serialization_TooManyElements {
            get {
                return ResourceManager.GetString("Serialization_TooManyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The implementation of the IObjectReference interface returns too many nested references to other objects that implement IObjectReference..
        /// </summary>
        public static string Serialization_TooManyReferences {
            get {
                return ResourceManager.GetString("Serialization_TooManyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No top object..
        /// </summary>
        public static string Serialization_TopObject {
            get {
                return ResourceManager.GetString("Serialization_TopObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top object cannot be instantiated for element &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_TopObjectInstantiate {
            get {
                return ResourceManager.GetString("Serialization_TopObjectInstantiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type code in stream &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_TypeCode {
            get {
                return ResourceManager.GetString("Serialization_TypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expected type..
        /// </summary>
        public static string Serialization_TypeExpected {
            get {
                return ResourceManager.GetString("Serialization_TypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load type {0} required for deserialization..
        /// </summary>
        public static string Serialization_TypeLoadFailure {
            get {
                return ResourceManager.GetString("Serialization_TypeLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is missing for member of type Object &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_TypeMissing {
            get {
                return ResourceManager.GetString("Serialization_TypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid read type request &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_TypeRead {
            get {
                return ResourceManager.GetString("Serialization_TypeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid write type request &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_TypeWrite {
            get {
                return ResourceManager.GetString("Serialization_TypeWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform fixup..
        /// </summary>
        public static string Serialization_UnableToFixup {
            get {
                return ResourceManager.GetString("Serialization_UnableToFixup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized..
        /// </summary>
        public static string Serialization_UnknownMemberInfo {
            get {
                return ResourceManager.GetString("Serialization_UnknownMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueType fixup on Arrays is not implemented..
        /// </summary>
        public static string Serialization_ValueTypeFixup {
            get {
                return ResourceManager.GetString("Serialization_ValueTypeFixup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element &apos;{0}&apos;..
        /// </summary>
        public static string Serialization_XMLElement {
            get {
                return ResourceManager.GetString("Serialization_XMLElement", resourceCulture);
            }
        }
    }
}
